# First Play
- name: Play - Handle Files in all hosts
  hosts: all
  become: yes #change access level, so all tasks have the same priviledge 
  tasks:
  - name: all host are identified with a file
    copy:
      content: My family is {{ ansible_os_family }}
      dest: /family.txt
      mode: '777'

# Second play
- name: Play - for Alpines Nodejs app
  hosts: app_group
  tasks:
  - name: NodeJs is installed
    apk:
      name: "{{ item }}"
      update_cache: yes
      state: latest
    loop:
    - nodejs
    - nodejs-npm
  - name: app directory is created
    file:
      path: /node-app
      state: directory
  - name: app is installed
    template:
      src: app.js.j2
      dest: /node-app/app.js
  - name: app dependencies file is copied
    copy:
      src: package.json
      dest: /node-app/package.json
  - name: app dependencies are installed
    npm:
      path: /node-app
      state: present
      production: true
  - name: Install forever (to run Node.js app).
    npm: name=forever global=yes state=present
  
  - name: Check list of Node.js apps running.
    command: forever list
    register: forever_list
    changed_when: false

  - name: Start example Node.js app.
    command: forever start /node-app/app.js
    when: "forever_list.stdout.find('/node-app/app.js') == -1"

- name: Play - Install and configure Nginx as a Loadbalancer
  hosts: loadbalancer #want nginx downloaded in the localhost
  become: yes
  tasks:
    - name: Update cache
      apt: #to download linux modules, apt for ubuntu based
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present #latest version of the image
    
    - name: Copy the Nginx config file to /etc/nginx/sites-available
      copy:             #copy source file to dest file
        src: nginx.cfg
        dest: /etc/nginx/sites-available/nginx.cfg
      notify: Restart Nginx     #call handler to do its tasks

    - name: Create symlink of the config file at /etc/nginx/sites-enabled #create a link in the dest that points to the src

      file:
        src: /etc/nginx/sites-available/nginx.cfg
        dest: /etc/nginx/sites-enabled/default # "default" makes sure the link is put in the correct file
        state: link
      notify: Restart Nginx

  handlers: # only runs ONCE if it is called
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted