ungrouped:
  hosts:
    managedhost-app-1:
      ansible_host: 0.0.0.0 #IP address of host
      ansible_connection: ssh
      ansible_port: 2223
      ansible_user: root #level of access that the app has

    managedhost-app-2:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2224
      ansible_user: root

    managedhost-app-3:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2225
      ansible_user: root

    loadbalancer:
      ansible_host: 0.0.0.0
      ansible_connection: local #connecting to localhost instead of ssh
      ansible_port: 80
      ansible_user: root

app_group:
  hosts:
    managedhost-app-1:
    managedhost-app-2:
    managedhost-app-3: